name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test -- --watchAll=false --passWithNoTests

      - name: Build React App
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t react-ecommerce:${{ github.sha }} .